"""
End-to-End Integration Test: Layer 3 (Rainfall) -> Layer 4 (Runoff) -> Layer 5 (Surface Storage & Routing).
"""

import pytest
import math
from flood_engine.grid import ComputationalGrid
from flood_engine.d8 import D8Terrain
from flood_engine.runoff import RunoffEngine
from flood_engine.surface import SurfaceStorageEngine
from replay.rainfall import load_rainfall_replay


def test_end_to_end_layer3_to_layer4_to_layer5():
    """
    Simulates complete pipeline:
    1. Layer 3 loads storm_01.json (2, 4, 6 mm)
    2. Layer 4 RunoffEngine computes incremental direct runoff volume m³ per cell
    3. Layer 5 SurfaceStorageEngine routes runoff downhill along D8 terrain
    4. Verifies mass conservation across entire system
    """
    # 1. Setup Layer 1 Grid & Layer 2 D8 Terrain
    grid = ComputationalGrid.create_synthetic_demo_grid(rows=6, cols=6, resolution_m=10.0)
    terrain = D8Terrain.compute_from_grid(grid)

    # 2. Setup Layer 4 Runoff Engine
    cell_areas = {cid: grid.cell_area_m2 for cid in terrain.cells.keys()}
    runoff_engine = RunoffEngine(
        cell_areas_m2=cell_areas,
        default_cn=90.0,
        expected_timestep_seconds=60,
    )

    # 3. Setup Layer 5 Surface Engine
    surface_engine = SurfaceStorageEngine(
        grid=grid,
        terrain=terrain,
        expected_timestep_seconds=60,
    )

    # 4. Load Layer 3 Rainfall Replay
    replay = load_rainfall_replay("data/replay/rainfall/storm_01.json")

    # 5. Run end-to-end simulation
    for rain_step in replay.replay():
        # Layer 4 Runoff Step
        r_step = runoff_engine.process_replay_step(rain_step)
        runoff_vols = {cid: cs.runoff_volume_m3 for cid, cs in r_step.cell_states.items()}

        # Layer 5 Surface Storage Step
        s_step = surface_engine.step(
            timestamp_seconds=rain_step.timestamp_seconds,
            runoff_volume_m3_by_cell=runoff_vols,
        )

        assert abs(s_step.mass_balance_error_m3) <= 1e-5

    # 6. Verify end-to-end mass balance
    r_bal = runoff_engine.mass_balance()
    s_bal = surface_engine.mass_balance()

    # Total runoff generated by Layer 4 must equal total runoff input ingested by Layer 5
    assert math.isclose(
        r_bal["cumulative_direct_runoff_volume_m3"],
        s_bal["cumulative_runoff_input_m3"],
        rel_tol=1e-5,
    )

    assert s_bal["is_conserved"] is True
    assert s_bal["current_surface_storage_m3"] > 0.0
